# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'calc_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for calc_test
  pod "CircleMenu"

  target 'calc_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'calc_testUITests' do
    # Pods for testing
  end

end
